version: "3.3"
services:
  dev-container:
    image: xuntian/npl-runtime
    volumes:
      - container:/project/wikicraft
      - ./container:/script
    command: /script/update.sh dev
  dev-server:
    image: xuntian/npl-runtime
    volumes:
      - container:/project/wikicraft
      - ./server:/script
    # link by nginx server
    #ports:
      #- "8900:8900"
    command: /script/start.sh dev

  test-container:
    image: node
    volumes:
      - container:/project/wikicraft
      - ./container:/script
    command: /script/update.sh test
  test-server:
    image: xuntian/npl-runtime
    volumes:
      - container:/project/wikicraft
      - ./server:/script
    # link by nginx server
    #ports:
      #- "8099:8099"
    command: /script/start.sh test

  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    links:
      - dev-server
      - test-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/keepwork.template:/etc/nginx/conf.d/keepwork.template
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - DEV_ADDRESS=dev.keepwork.com
      - DEV_HOST=dev-server
      - DEV_PORT=8900
      - TEST_ADDRESS=test.keepwork.com
      - TEST_HOST=test-server
      - TEST_PORT=8099
    command: /bin/bash -c "envsubst </etc/nginx/conf.d/keepwork.template >/etc/nginx/conf.d/keepwork.conf && nginx -g 'daemon off;'"

volumes:
  container:





