version: "3.3"
services:
  mysql-server:
    image: mysql/mysql-server
    networks:
      monit_net:
        ipv4_address: 172.228.0.2
        aliases:
          - database
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
  zabbix-server:
    depends_on:
      - mysql-server
    image: zabbix/zabbix-server-mysql
    networks:
      monit_net:
        ipv4_address: 172.228.0.3
        aliases:
          - server
    environment:
      - DB_SERVER_HOST=172.228.0.2
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - zabbix-server:/var/lib/zabbix
  zabbix-web:
    depends_on:
      - mysql-server
      - zabbix-server
    image: zabbix/zabbix-web-nginx-mysql
    networks:
      monit_net:
        ipv4_address: 172.228.0.4
        aliases:
          - web
    environment:
      - ZBX_SERVER_HOST=172.228.0.3
      - DB_SERVER_HOST=172.228.0.2
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
      - PHP_TZ="Asia/Shanghai"
    ports:
      - "7000:80"

networks:
  monit_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.228.0.0/24

volumes:
  zabbix-server:
