version: "3.3"
services:
  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    links:
      # FIXME hardcode here, link to keepwork server
      - keepwork-dev-server
      - keepwork-test-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/keepwork.template:/etc/nginx/conf.d/keepwork.template
      - ./nginx/html:/usr/share/nginx/html
    environment:
      # thanks https://stackoverflow.com/questions/40619582/how-can-i-escape-a-dollar-sign-in-a-docker-compose-file
      - DOLLAR=$$
      - DEV_ADDRESS=dev.keepwork.com
      - DEV_HOST=keepwork-dev-server
      - DEV_PORT=8900
      - TEST_ADDRESS=test.keepwork.com
      - TEST_HOST=keepwork-test-server
      - TEST_PORT=8099
    command: /bin/bash -c "envsubst </etc/nginx/conf.d/keepwork.template >/etc/nginx/conf.d/keepwork.conf && nginx -g 'daemon off;'"

