version: "3.3"
services:
  jenkins:
    build:
      context: ./jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
