version: "3.3"
services:
  jenkins:
    build:
      context: ./jenkins
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /services:/services
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
